---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: page-secrets
  namespace: prod
spec:
  encryptedData:
    ADMIN_TOKEN_SHA256: AgBArcydlmxSXhba97c2xXaRea2oHz/Nt64UTc34DDsGijjPb4QL09dZ14M2wkNpd15WVGVFwgA3yURbd1w0hEygyZTZ0saAtdj3+4j5q9ipuw5WeO4siwaTBq3Xl0InsSW/C6rUbU0x5j81WsFHmggzw4Bv1CwY4OpyuC9FjBKStsHuNXyFUQTBTO4XORb4szVQFUK7UhRrcuCrv5fVy6wkRBg00/1RojwWhDoJpbiOzjfCbpTLTKj3vL2op8H5RmjQfvnIAc/XNOkT1aDkEfKoMZ7ppF+podJ6nMf/uySMkT7JZXPcCVnIvMFTV8OEjdEUCiNi0esWbZGQhOi/eKcm4AqlNLBKsBhaqrO8Vo204olLvrjFixLhbFPTMr/9TbfpAZkM1VGZm2QtK3d4fwh+F8ziXuvO3lqBzSqj7Z8Ba2QMJHiQTgVr4h+ewZ1XwGMVaYek/+w2Ru7StZx5U6iyIx/V6Ek2VDcLHoQZA+187/GN+ctFNkEn8YfsL4fzOGJMlz1MI6xil2PHza4PKPA8kEs8AFwsINKytok7B6NQKjJwDqRFlzA/kQUG02gqSL8sBnUas8ExjHllv7atTBMcpklPtk/l5vMafrlZNQOdINiKMuMYmhWhWpAoJyS5o0D3xkgyCP3bS2MWVS0Gz52Wz/L6yAgxy4xy6IMExPg/Jp/yHVdn9M6A5s7LRmzKCa3BeRciu5KxV3BLviNt9g4a8Vx6snVjol/UrH+btQuRCqq6TpgntnvbpkDVmfYyWujXjFhUe5v32T82vWhY8COL
  template:
    metadata:
      name: page-secrets
      namespace: prod
    type: Opaque
